Update tools to latest versions (#756)
rellic:
* Updated to latest `master` commit
* Remove `|| true` to make sure tests stay passing

remill:
* Updated to latest `master` commit
* Updated vcpkg portfile to latest released version 4.0.24
* Allow failure of tests on aarch64. See https://github.com/lifting-bits/remill/issues/518

anvill:
* Updated to latest `master` commit
* Add other submodule for anvill version compatible with mcsema
* Don't install Python3 components since we don't test them

mcsema:
* Updated to latest `master` commit
* Add pinned anvill version submodule
* Add two smoketests
* Allow failure for `x86` smoketest on aarch64 host. See https://github.com/lifting-bits/mcsema/issues/753

diff --git a/.github/workflows/vcpkg_ci_linux.yml b/.github/workflows/vcpkg_ci_linux.yml
--- a/.github/workflows/vcpkg_ci_linux.yml
+++ b/.github/workflows/vcpkg_ci_linux.yml
@@ -78,7 +78,7 @@ jobs:
 
       - uses: actions/checkout@v2.3.4
         with:
-          submodules: true
+          submodules: recursive
 
       - name: Read vcpkg Info
         id: vcpkg_info
@@ -139,7 +139,7 @@ jobs:
             @dependencies.txt
 
       - name: 'Export Packages'
-        if: contains(github.event.head_commit.message, 'debug artifacts') || github.event.release
+        if: contains(env.COMMIT_MESSAGE, 'debug artifacts') || github.event.release
         shell: 'bash'
         run: |
           apt-get update
@@ -150,7 +150,7 @@ jobs:
           ./emit_artifacts.sh ${{ env.ARTIFACT_NAME }}
 
       - uses: actions/upload-artifact@v2.2.3
-        if: "contains(github.event.head_commit.message, 'debug artifacts')"
+        if: contains(env.COMMIT_MESSAGE, 'debug artifacts') || github.event.release
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: ${{ env.ARTIFACT_NAME }}
@@ -210,7 +210,7 @@ jobs:
             ..
           cmake --build .
           cmake --build . --target install
-          ../scripts/roundtrip.py ./tools/rellic-decomp-* ../tests/tools/decomp "${VCPKG_ROOT}/installed/${{ matrix.host.triplet }}/tools/${{ matrix.llvm }}/clang" || true
+          ../scripts/roundtrip.py ./tools/rellic-decomp-* ../tests/tools/decomp "${VCPKG_ROOT}/installed/${{ matrix.host.triplet }}/tools/llvm/clang"
 
       - name: 'Test remill build'
         shell: 'bash'
@@ -226,7 +226,13 @@ jobs:
           cmake --build .
           cmake --build . --target install
           cmake --build . --target test_dependencies
-          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test || true
+          # See issue https://github.com/lifting-bits/remill/issues/518 for
+          # failing aarch64 tests
+          if [ ${{ matrix.host.arch }} == "arm64" ] ; then
+            env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test || true
+          else
+            env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test
+          fi
 
       # Only for LLVM-11 right now...
       - name: 'Anvill build - vcpkg remill'
@@ -240,6 +246,7 @@ jobs:
             -DCMAKE_VERBOSE_MAKEFILE=ON \
             -DVCPKG_ROOT="${VCPKG_ROOT}" \
             -DANVILL_ENABLE_INSTALL_TARGET=ON \
+            -DANVILL_ENABLE_PYTHON3_LIBS=OFF \
             -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
             ..
           cmake --build .
@@ -256,6 +263,26 @@ jobs:
           cmake -G Ninja \
             -DCMAKE_VERBOSE_MAKEFILE=ON \
             -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
+            -DVCPKG_ROOT="${VCPKG_ROOT}" \
+            -DANVILL_ENABLE_INSTALL_TARGET=ON \
+            -DANVILL_ENABLE_PYTHON3_LIBS=OFF \
+            -Dremill_DIR="$(pwd)/../../remill/build/install/lib/cmake/remill" \
+            ..
+          cmake --build .
+          cmake --build . --target install
+          ./install/bin/anvill-decompile-json-* -spec ../tools/decompile-json/tests/specs/ret0.json -bc_out ./ret0.bc -ir_out ret0.ir
+
+      - name: 'Anvill-McSema build - custom remill'
+        shell: 'bash'
+        if: ${{ matrix.llvm != 'llvm-12' }}
+        run: |
+          cd anvill-mcsema
+          rm -rf build
+          mkdir -p build && cd build
+          cmake -G Ninja \
+            -DCMAKE_VERBOSE_MAKEFILE=ON \
+            -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
+            -DVCPKG_ROOT="${VCPKG_ROOT}" \
             -DANVILL_ENABLE_INSTALL_TARGET=ON \
             -Dremill_DIR="$(pwd)/../../remill/build/install/lib/cmake/remill" \
             ..
@@ -265,7 +292,7 @@ jobs:
 
       - name: 'Test mcsema build'
         shell: 'bash'
-        if: ${{ matrix.llvm == 'llvm-11' }}
+        if: ${{ matrix.llvm != 'llvm-12' }}
         run: |
           cd mcsema
           rm -rf build
@@ -273,11 +300,22 @@ jobs:
           cmake -G Ninja \
             -DCMAKE_VERBOSE_MAKEFILE=ON \
             -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
+            -DVCPKG_ROOT="${VCPKG_ROOT}" \
             -Dremill_DIR="$(pwd)/../../remill/build/install/lib/cmake/remill" \
-            -Danvill_DIR="$(pwd)/../../anvill/build/install/lib/cmake/anvill" \
+            -Danvill_DIR="$(pwd)/../../anvill-mcsema/build/install/lib/cmake/anvill" \
             ..
           cmake --build .
           cmake --build . --target install
+
+          ./install/bin/mcsema-lift-* --version
+          ./install/bin/mcsema-lift-* --arch amd64 --os linux --cfg ../tests/test_suite_generator/generated/prebuilt_cfg/amd64/linux/cfg/hello_world --output hello_world.bc
+
+          # See https://github.com/lifting-bits/mcsema/issues/753
+          if [ ${{ matrix.host.arch }} == "arm64" ] ; then
+            ./install/bin/mcsema-lift-* --arch x86 --os linux --cfg ../tests/test_suite_generator/generated/prebuilt_cfg/x86/linux/cfg/hello_world --output hello_world.bc || true
+          else
+            ./install/bin/mcsema-lift-* --arch x86 --os linux --cfg ../tests/test_suite_generator/generated/prebuilt_cfg/x86/linux/cfg/hello_world --output hello_world.bc
+          fi
 
       - name: Publish Release Assets
         if: |
