Inline conditionals for arm/x86-64 into their respective files

diff --git a/.github/workflows/vcpkg_ci_aws_amd64.yml b/.github/workflows/vcpkg_ci_aws_amd64.yml
--- a/.github/workflows/vcpkg_ci_aws_amd64.yml
+++ b/.github/workflows/vcpkg_ci_aws_amd64.yml
@@ -116,9 +116,6 @@ jobs:
         shell: 'bash'
         run: |
           export VCPKG_DISABLE_METRICS=1
-          if [ ${{ matrix.host.arch }} == "arm64" ] ; then
-            export VCPKG_FORCE_SYSTEM_BINARIES=1
-          fi
 
           # Setup NuGet authentication
           mono "$(${VCPKG_ROOT}/vcpkg fetch nuget | tail -n 1)" sources add \
@@ -202,13 +199,9 @@ jobs:
           scripts/build-preset.sh debug
           pushd ${INSTALL_DIR}/build/remill
           cmake --build . --parallel --target test_dependencies
-          # See issue https://github.com/lifting-bits/remill/issues/518 for
-          # failing aarch64 tests
-          if [ ${{ matrix.host.arch }} == "arm64" ] ; then
-            env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --parallel --target test || true
-          else
-            env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --parallel --target test || true
-          fi
+          # The ||true is ther since we are Failing some tests on AWS (issue #583)
+          # https://github.com/lifting-bits/remill/issues/583
+          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --parallel --target test || true
           popd
 
       - name: 'Anvill build'
