Revert "Test remill with LLVM 16"
This reverts commit fe539b52180eb00406db42428cfc06e9d68b083b.

diff --git a/.github/workflows/vcpkg_ci_amd64.yml b/.github/workflows/vcpkg_ci_amd64.yml
--- a/.github/workflows/vcpkg_ci_amd64.yml
+++ b/.github/workflows/vcpkg_ci_amd64.yml
@@ -207,7 +207,7 @@ jobs:
       - name: 'Remill build'
         shell: 'bash'
         working-directory: remill
-        # if: contains(matrix.llvm, 'llvm-15')
+        if: contains(matrix.llvm, 'llvm-15')
         run: |
           cmake -G Ninja \
             -DCMAKE_VERBOSE_MAKEFILE=ON \
@@ -222,9 +222,10 @@ jobs:
       - name: 'Remill test'
         shell: 'bash'
         working-directory: remill/build
-        # if: contains(matrix.llvm, 'llvm-15')
+        if: contains(matrix.llvm, 'llvm-15')
         run: |
-          env CTEST_OUTPUT_ON_FAILURE=1 ctest .
+          # Some tests fail on ubuntu 22.04
+          env CTEST_OUTPUT_ON_FAILURE=1 ctest . || true
 
       - name: 'Anvill build'
         shell: 'bash'
